# Generated by Django 3.0.7 on 2020-07-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200715_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
