# Generated by Django 3.0.7 on 2020-07-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(default='default1.png', upload_to='qr_codes'),
        ),
    ]
